# 卵を落とす問題
100階建ての建物があります。N階以上の他kさから卵を落とすと卵は割れてしまいます。N階より下からであれば卵は割れません。２つの卵を使い、落とす回数をできるだけ少なくなるようにNを見つけてください。

# 考え方
2分探索を１つ目の卵を使い探索する。卵が割れたら候補の一番下から１つづつ落として調べていく。

In [119]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as stats

In [64]:
def is_safe(floor, threshold):
  if floor < threshold:
    return True
  else:
    return False

In [141]:
def check(floors, number_of_egg, threshold):
  if number_of_egg == 0:
    # 現在の最小の階数-1が閾値となる階数
    print(floors)
    return floors[0]
  elif number_of_egg == 1:
    # 残り一つしか卵が残ってない場合は小さい階から順番に検査していく
    if not(is_safe(floors[0], threshold)):
      number_of_egg = number_of_egg - 1

    if(len(floors) == 1):
        return check(floors, 0, threshold)
    
    floors = np.delete(floors, np.s_[:1:])
    return check(floors, number_of_egg, threshold)
  else:
    # 卵が２つ残ってる時は
    if not(is_safe(floors[int(len(floors)/2)], threshold)):
      number_of_egg = number_of_egg - 1

    floors = np.delete(floors, np.s_[:int(len(floors)/2):])
    # 上半分を検査していく
    return check(floors, number_of_egg, threshold)

column = ["閾値", "結果"]
df1 = pd.DataFrame(data=[], columns=column)
for x in range(10):
  result = check(np.array(range(10)), 2, x)
  df1 = df1.append(pd.DataFrame(data=[[str(x), str(result)]], columns=column))

df1

[6 7 8 9]
[6 7 8 9]
[6 7 8 9]
[6 7 8 9]
[6 7 8 9]
[6 7 8 9]
[8 9]
[8 9]
[9]
[9]


閾値 結果
0  0  6
0  1  6
0  2  6
0  3  6
0  4  6
0  5  6
0  6  8
0  7  8
0  8  9
0  9  9

In [84]:
arr = np.array(range(10))
np.delete(arr, np.s_[:1:])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])